# Generated by Django 3.2.16 on 2022-11-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kpiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS', models.CharField(max_length=20)),
                ('kernel', models.CharField(max_length=20)),
                ('server_info', models.CharField(max_length=20)),
                ('cpu_info', models.CharField(max_length=20)),
                ('bios_info', models.CharField(max_length=20)),
                ('gpu_info', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('gpu_driver', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kpiConfiguration',
            },
        ),
    ]
